# -*- coding: utf-8 -*-
"""James_HW5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_Nqmhv2xZ28LWMesoxoVn1Y9dyygkea
"""

# Commented out IPython magic to ensure Python compatibility.
# Installs medmnist library
# %pip install medmnist -q

# Loads medmnist dataset
import medmnist
from medmnist import PneumoniaMNIST
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

# Imports PyTorch Deep Learning Modules and matplotlib
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import matplotlib.pyplot as plt

# Defines transformations
data_transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

# Downloads and loads training, validation, and test data sets
train_dataset = PneumoniaMNIST(split='train', transform=data_transform, download=True)
val_dataset = PneumoniaMNIST(split='val', transform=data_transform, download=True)
test_dataset = PneumoniaMNIST(split='test', transform=data_transform, download=True)


# Wraps data sets in PyTorch DataLoaders for model
batch_size = 128
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(dataset=val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False)


# Defines the CNN Model
class PneumoniaCNN(nn.Module):
    def __init__(self):
        super(PneumoniaCNN, self).__init__()

        # Convolutional Block 1
        self.conv_block1 = nn.Sequential(
            nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        # Convolutional Block 2
        self.conv_block2 = nn.Sequential(
            nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        # Connected Layers
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32 * 7 * 7, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, 2)
        )

    def forward(self, x):
        x = self.conv_block1(x)
        x = self.conv_block2(x)
        x = self.classifier(x)
        return x

# Initialize model and move to available CPU device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PneumoniaCNN().to(device)


# Set Up Loss and Optimizer evaluation metrics
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)


# Defines training of model with PneumoniaMNIST training data
def train_model(model, train_loader, val_loader, criterion, optimizer, num_epochs=10):

    # Initialize dictionaries for plotting metrics
    history = {
        'train_loss': [],
        'val_loss': [],
        'val_accuracy': []
    }

    for epoch in range(num_epochs):
        model.train()
        running_loss = 0.0

        # Training Phase
        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.view(-1).long().to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        # Validation Phase
        model.eval()
        val_loss = 0.0
        correct = 0
        total = 0

        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.view(-1).long().to(device)
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                val_loss += loss.item()
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        # Calculates summary metrics for training and validation sets
        epoch_train_loss = running_loss / len(train_loader)
        epoch_val_loss = val_loss / len(val_loader)
        val_accuracy = 100 * correct / total

        # Saves metrics for plotting
        history['train_loss'].append(epoch_train_loss)
        history['val_loss'].append(epoch_val_loss)
        history['val_accuracy'].append(val_accuracy)

        # Prints summary metrics across training cycles
        print(f"Epoch [{epoch+1}/{num_epochs}] "
              f"Train Loss: {epoch_train_loss:.4f} | "
              f"Val Loss: {epoch_val_loss:.4f} | "
              f"Val Accuracy: {val_accuracy:.2f}%")

    return history

# Executes training cycles
history = train_model(model, train_loader, val_loader, criterion, optimizer, num_epochs=10)
history

# Plots training performance
epochs = range(1, len(history['train_loss']) + 1)
plt.figure(figsize=(12, 5))

# Left Plot for Training and Validation Loss
plt.subplot(1, 2, 1)
plt.plot(epochs, history['train_loss'], 'bo-', label='Training Loss')
plt.plot(epochs, history['val_loss'], 'ro-', label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# Right Plot for Validation Accuracy
plt.subplot(1, 2, 2)
plt.plot(epochs, history['val_accuracy'], 'go-', label='Validation Accuracy')
plt.title('Validation Accuracy over Time')
plt.xlabel('Epochs')
plt.ylabel('Accuracy (%)')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()


# Evaluation of model with test data
def evaluate_model(model, test_loader, criterion):
    model.eval()
    test_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.view(-1).long().to(device)
            outputs = model(inputs)

            # Calculates loss in test data
            loss = criterion(outputs, labels)
            test_loss += loss.item()

            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    # Provides summary statistics of model on test data
    print(f"Test Accuracy: {100 * correct / total:.2f}%")
    print(f"Test Loss: {test_loss / len(test_loader):.4f}")

# Executes model on test data
evaluate_model(model, test_loader, criterion)